config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :attributes
  end
  root 'pages#home'
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, Type
    can :read, Attribute

    can :manage, Type, user_id: user.id
    can :manage, Attribute
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
class Attribute < ApplicationRecord
  belongs_to :type
  has_one_attached :icon
  validates :name, presence: true
  validates :numerical, presence: true, numericality: { only_integer: true }
end

app/models/type.rb
class Type < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :character_attributes, class_name: 'Attribute', dependent: :delete_all
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :types

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  validate :validate_username
  validates :email, presence: true
  validates :password, presence: true

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    errors.add(:username, :invalid) if User.exists?(email: username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def after_sign_in_path_for(_resource)
    root_path(current_user)
  end

  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Please Sign In or Sign Up to view that page!'
  end
end

app/controllers/attributes_controller.rb
class AttributesController < ApplicationController
  load_and_authorize_resource
  before_action :set_type, except: [:destroy]
  respond_to :js, :html

  def index
    @attributes = @type.character_attributes.order('created_at DESC').page(params[:page]).per(4)
  end

  def create
    @attribute = @type.character_attributes.new(attribute_params)
    saved = @attribute.save
    render :new unless saved
  end

  def update
    updated = @attribute.update(attribute_params)
    render :edit unless updated
  end

  def destroy
    @attribute.destroy
  end

  private

  def set_type
    @type = Type.find(params[:type_id])
  end

  def attribute_params
    params.require(:attribute).permit(:name, :numerical, :type_id, :icon)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  load_and_authorize_resource
  respond_to :js, :html

  def index
    @types = @types.where(user_id: current_user).order('created_at DESC').page(params[:page]).per(4)

    @types = Type.all.order('created_at DESC').page(params[:page]).per(4) if params[:show_all] == 'true'
  end

  def create
    @type = current_user.types.new(type_params)
    saved = @type.save
    render :new unless saved
  end

  def update
    updated = @type.update(type_params)
    render :edit unless updated
  end

  def destroy
    @type.destroy
  end

  private

  def type_params
    params.require(:type).permit(:name, :image)
  end
end

app/views/attributes/_attribute.html.erb
<tr id="<%= dom_id attribute %>">
    <td><%= attribute.name %></td>
    <td><%= attribute.numerical %></td>
    <td><%= image_tag(attribute.icon, style: "width: 40px") if attribute.icon.attached? && attribute.icon.persisted?%></td>
    <td><button class="show-button-attribute"><%= link_to 'Show', type_attribute_path(@type, attribute), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-show'} %></button></td>
    <td><button class="edit-button-attribute"><%= link_to 'Edit', edit_type_attribute_path(@type, attribute), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-show'} %></button></td>
    <td><button class="destroy-button-attribute"><%= link_to 'Destroy', [@type, attribute], method: :delete, data: { remote: true }, class: "delete" %></button></td>
</tr>

app/views/attributes/_edit.html.erb
<div class="modal-header">
  <h4 class="modal-title">Edit Attribute</h4>
</div>

<div class="modal-body">
  <div class="center">
    <%= form_with(model: [@type, @attribute], remote: true) do |form| %>
      <div class="login">
        <% if @attribute.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>
            <ul>
              <% @attribute.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.hidden_field :type_id, value: @type.id %>
        </div>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name,  id: "name-field2" %>
        </div>

        <div class="field">
          <%= form.label :numerical %>
          <%= form.text_field :numerical, id: 'numerical-edit-field' %>
        </div>

        <div class="field limit_image" id="image-attribute-edit">
          <%= form.label :icon %> </br >
          <% if @attribute.icon.attached? && @attribute.icon.persisted? %>
            <%= image_tag @attribute.icon %>
          <% else %>
            <%= image_tag("download.png", :alt => "no image", :id => "update-image-attribute-new") %>
          <% end %>
          <%= form.file_field :icon, id: 'icon-edit-attribute' %>
        </div>

        <div class="actions">
          <button id="update-button-attribute">
            <%= form.submit %>
          </button>
        </div>

        </div>
    <% end %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close-button-edit-attribute">Close</button>
</div>

app/views/attributes/_index.html.erb
<div class="modal-header">
  <h4 class="modal-title h1-value">List of Character Attributes for Type: <%=@type.name%></h4>
</div>

<div class="modal-body">
  <p id="notice"><%= notice %></p>

  <div id="paginator-attributes">
    <%=paginate @attributes,  :remote => true %>
  </div>

  <table id="attributes_table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Numerical</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody id="attributes-render">
      <%= render partial: 'attribute', collection: @attributes %>
    </tbody>
  </table>

</div>

<%= link_to 'New Attribute', new_type_attribute_path(@type), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-new-attribute', 'class'=> "new-attribute-button"} %>
<%= render 'modals' %>

<div id="modal-window-new-attribute" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered max-width-1000">
    <div class="modal-content"></div>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close-button-index">Close</button>
</div>

<script>
    var pathname = window.location.pathname; // Returns path only (/path/example.html)
    var search_from_url = window.location.search
    var sum = pathname + search_from_url
    if (sum == '/types?show_all=true' ){
        $(".edit-button-attribute" ).hide();
        $(".destroy-button-attribute").hide();
        $(".new-attribute-button").hide();
    }
</script>

app/views/attributes/_modals.html.erb
<div id="modal-window-new-attribute" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

<div id="modal-window-edit-attribute" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

<div id="modal-window-show-attribute" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

app/views/attributes/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title">Create New Attribute</h4>
</div>

<div class="modal-body">
  <div class="center">
      <%= form_with(model: [@type, @attribute], remote: true) do |form| %>

      <div class="login">
        <% if @attribute.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>

            <ul>
              <% @attribute.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div  class="red-collor-letter">
          <%= notice %>
        </div>

        <div class="field" id="defined_type_id">
          <%= form.hidden_field :type_id, value: @type.id %>
        </div>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, id: "name-field1" %>
        </div>

        <div class="field">
          <%= form.label :numerical, 'Numerical value' %>
          <%= form.number_field :numerical, id: "numerical-field-new" %>
        </div>

        <div class="field limit_image", id="image-new-attribute">
          <%= form.label :icon %>
          <% if @attribute.icon.attached? && @attribute.icon.persisted? %>
            <%= image_tag @attribute.icon %>
          <% else %>
            <%= image_tag("download.png", :alt => "no image", :id => "image-attribute-append") %>
          <% end %>

          <%= form.file_field :icon, id: 'icon-attribute-new-id' %>
        </div>

        <div class="actions style-button-create">
          <button id="submit-button-attribute">
          <%= form.submit %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close-button-new-attribute">Close</button>
</div>

app/views/attributes/_show.html.erb
<div class="modal-header">
  <h4 class="modal-title">Character Attribute: <%=@attribute.name%></h4>
</div>

<div class="modal-body">
  <div class="login">
    <p id="notice"><%= notice %></p>
      <p>
        <strong>Name:</strong>
        <%= @attribute.name %>
      </p>
      <p>
        <strong>Numerical:</strong>
        <%= @attribute.numerical %>
      </p>
      <p>
        <strong>Icon:</strong>
      <div style="width:200px; height: auto">
        <%= image_tag(@attribute.icon, style: "width: 100%") if @attribute.icon.attached? %>
      </div>
    </p>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="button-close-show-attribute">Close</button>
</div>

app/views/attributes/create.js.erb
$('#attributes_table').prepend('<%= j render partial: "attribute", locals: {attribute: @attribute} %>');

var rowCount = $('#attributes_table tr').length;
if (rowCount > 5){
    $('#attributes_table tr').last().remove();
}

$('#attributes-render tr').first().addClass("highlight");
setTimeout(function() {
    $('#attributes-render tr').first().removeClass('highlight');
}, 4000);

app/views/attributes/destroy.js.erb
$('.delete').bind('ajax:success', function(){
   $(this).closest('tr').fadeOut();
});

var rowCount = $('#attributes-render tr').length;
if (rowCount < 5){
    if($("#paginator-attributes").children('.pagination').length == 1){
        window.location.reload();
    }
}

app/views/attributes/edit.js.erb
$('#modal-window-edit-attribute').find(".modal-content").html("<%= j (render 'edit', attribute: @attribute) %>");
$('#modal-window-edit-attribute').modal('show');

function readURL_attribute(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#image-attribute-edit img').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$("#icon-edit-attribute").change(function(){
    readURL_attribute(this);
});

$("#close-button-edit-attribute").click(function(e){
    $('#modal-window-edit-attribute').modal('hide');
});

$('#update-button-attribute').click(function(){
    if($('#name-field2').val() != '' && $('#numerical-edit-field').val() != ''){
        $('#modal-window-edit-attribute').modal('hide');
    }
});

app/views/attributes/index.js.erb
$('#modal-window-all-attributes').find(".modal-content").html("<%= j (render 'index') %>");
$('#modal-window-all-attributes').modal('show');

$("#attributes-render").html("<%= j render partial: 'attribute', collection: @attributes %>");
$("#paginator-attributes").html("<%= j(paginate(@attributes, :remote => true))%>");

$("#close-button-index").click(function(e){
    $('#modal-window-all-attributes').modal('hide');
});

var pathname = window.location.pathname;
var search_from_url = window.location.search
var sum = pathname + search_from_url
if (sum == '/types?show_all=true' ){
  $(".edit-button-attribute").hide();
  $(".destroy-button-attribute").hide();
  $(".new-attribute-button").hide();
}

app/views/attributes/new.js.erb
$('#modal-window-new-attribute').find(".modal-content").html("<%= j (render 'new', attribute: @attribute) %>");
$('#modal-window-new-attribute').modal('show');

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#image-new-attribute img').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$("#icon-attribute-new-id").change(function(){
    readURL(this);
});

$("#close-button-new-attribute").click(function(e){
    $('#modal-window-new-attribute').modal('hide');
});

$('#submit-button-attribute').click(function(){
    if($('#name-field1').val() != '' && $('#numerical-field-new').val() != ''){
        $('#modal-window-new-attribute').modal('hide');
    }
});

app/views/attributes/show.js.erb
$('#modal-window-show-attribute').find(".modal-content").html("<%= j (render 'show', attribute: @attribute) %>");
$('#modal-window-show-attribute').modal('show');

$("#button-close-show-attribute").click(function(e){
    $('#modal-window-show-attribute').modal('hide');
});

app/views/attributes/update.js.erb
$('#<%= dom_id @attribute %>').replaceWith('<%= j render partial: "attribute", locals: {attribute: @attribute} %>');
$('#<%= dom_id @attribute %>').addClass("highlight");

setTimeout(function() {
    $( "tr" ).removeClass('highlight');
}, 1000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RpgEditor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<% if !current_user %>
  <div class="header">
    <div class="screen-page">
        <h1>Welcome to RPG Game Editor!</h1>
        <h2>Please sign in or sign up: </h2>
        <div class="button-right">
          <%= link_to "Sign Up", new_user_registration_path, class: "sign-in-type-button" %>
        </div> </br>
        <div class="button-right">
          <%= link_to "Sign In", new_user_session_path, class: "sign-up-type-button" %>
        </div> </br>
    </div>
  </div>
  <div id="notice-id" class="red-collor-letter">
    <%= notice %>
  </div>
<% else %>
  <div class="header">
    <div class="screen-page">
        <div class="button-right">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-out-type-button" %>
        </div>
        <h1>Welcome to RPG Game Editor!</h1>
        <h2><%= current_user.username %>!</h2>
        <div class="button-right">
          <%= link_to "List of Created Types", types_path, class: "see-all-type-button" %>
        </div>
    </div>
  </div>
    </br>
  </div>
  <div class="hero-image">
    <p id="notice"><%= notice %></p>
  </br> </br> </br>
    <div>
      <%= link_to "Update Your Information", edit_user_registration_path, class: "update-info-user-button" %>
    </div>
  </div>
<% end %>

<script>
    setTimeout(function() {
      $("#notice-id").hide();
    }, 6000);
</script>

app/views/types/_edit.html.erb
<div class="modal-header">
  <h4 class="modal-title">Edit type</h4>
</div>
<div class="modal-body">
  <div class="center">
    <%= form_for(@type,  remote: true) do |form| %>
      <div class="login">

        <% if @type.errors.any? %>
          <div id="error_explanation" >
            <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>
            <ul>
              <% @type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>

        <div class="field limit_image" id="image-edit">
          <%= form.label :image %> </br >
          <% if @type.image.attached? && @type.image.persisted? %>
            <%= image_tag @type.image %>
          <% else %>
            <%= image_tag("download.png", :alt => "no image", :id => "type-image-update") %>
          <% end %>
          <%= form.file_field :image, id: 'edit-image-id-type' %>
        </div>

        <div class="actions style-button-edit">
          <button id="update-button">
            <%= form.submit %>
          </button>
        </div>

      </div>
    <% end %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close-button">Close</button>
</div>

app/views/types/_modals.html.erb
<div id="myModal" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

<div id="modal-window-edit" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

<div id="modal-window-show" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

<div id="modal-all-types" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content"></div>
  </div>
</div>

<div id="modal-window-all-attributes" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered max-width-1000">
    <div class="modal-content"></div>
  </div>
</div>

app/views/types/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title">Create new type</h4>
</div>
<div class="modal-body">
  <div class="center">
    <%= form_for(@type,  remote: true) do |form| %>

      <div class="login">
        <% if @type.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

            <ul>
              <% @type.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field" >
          <%= form.label :name %>
          <%= form.text_field :name, id: "name-field",autocomplete: "name"%>
        </div>

        <div class="field limit_image" id="image">
          <%= form.label :image %>   </br >
          <% if @type.image.attached? && @type.image.persisted? %>
            <%= image_tag @type.image %>
          <% else %>
            <%= image_tag("download.png", :alt => "no image", :id => "new-image-type-added") %>
          <% end %>
          <%= form.file_field :image, id: "type-image-id-new"%>
        </div>

        <div class="actions style-button-create">
          <button id="submit-button">
          <%= form.submit %>
          </button>
        </div>

      </div>
    <% end %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close-button-new-type">Close</button>
</div>

app/views/types/_show.html.erb
<div class="modal-header">
  <h4 class="modal-title">Type <%=@type.name%></h4>
</div>

<div class="modal-body">
  <div class="login">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @type.name %>
    </p>
    <p>
      <strong>Avatar:</strong>
    <div style="width:200px; height: auto">
      <%= image_tag(@type.image, style: "width: 100%") if @type.image.attached? %>
    </div>
    </p>
  </div>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" id="close-button-show-type">Close</button>
</div>

app/views/types/_type.html.erb
<tr id="<%= dom_id type %>">
  <td><%= type.name %></td>
  <td><%= image_tag(type.image,  style: "width: 50px") if type.image.attached? && type.image.persisted? %></td>
  <td><button class="show-button-type"><%= link_to 'Show',  type_path(type), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-show'}%></button></td>
  <td><button class="edit-button-type"><%= link_to 'Edit', edit_type_path(type), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-edit'} %></button></td>
  <td><button class="destroy-button-type"><%= link_to 'Destroy', type, method: :delete, data: { remote: true }, class: "delete" %></button></td>
  <td><button class="attributes-button-type"><%= link_to 'List of Attributes', type_attributes_path(:type_id => type.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-all-attributes'} %></button></td>
</tr>

app/views/types/create.js.erb
$('#types_table').prepend('<%= j render partial: "type", locals: {type: @type} %>');

var rowCount = $('#types-render tr').length;
if (rowCount > 4){
    $('#types_table tr').last().remove();
    if($("#paginator").children('.pagination').length == 0){
        window.location.reload();
    }
}

$('tr').eq(1).addClass("highlight");
setTimeout(function() {
    $( "tr" ).removeClass('highlight');
}, 3000);

app/views/types/destroy.js.erb
$('.delete').bind('ajax:success', function(){
   $(this).closest('tr').remove();
});

var rowCount = $('#types-render tr').length;
if (rowCount < 5){
    if($("#paginator").children('.pagination').length == 1){
        window.location.reload();
    }
}

app/views/types/edit.js.erb
$('#modal-window-edit').find(".modal-content").html("<%= j (render 'edit', type: @type) %>");
$('#modal-window-edit').modal('show');

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#image-edit img').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$("#edit-image-id-type").change(function(){
    readURL(this);
});

$("#close-button").click(function(e){
    $('#modal-window-edit').modal('hide');
});

$('#update-button').click(function(){
    if($('#type_name').val() != '') {
        $('#modal-window-edit').modal('hide');
    }
});

app/views/types/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<div class="header">
  <div class="screen-page">
    <h1>RPG game editor</h1>
      </br>
      <div>
        <%= link_to "Go Back", root_path, class: "go-back-button" %>
      </div>
  </div>
</div>

<div class="content">
  <section class="content">
    <div class="container">
      <div class="page-header">
      <span>
          <%= link_to 'Show all created types', types_path(:show_all => true), class: "all-type-button"%>
        <%= link_to 'Show types you created', types_path(:show_all => false), class: "all-type-button"%>
    </span>
        </br></br>
        <h1>Character Types</h1>
      </div>
    </div>
    <div id="paginator">
      <%= paginate @types, :remote => true%>
    </div>

    <div class="bottom-margin">
      <table id="types_table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Avatar</th>
          <th colspan="4"></th>
        </tr>
        </thead>

        <tbody id="types-render">
        <%= render @types %>
        </tbody>
      </table>
    </div>
    <br>
    <%= link_to 'Create New Type', new_type_path(@type), {:remote => true, 'data-toggle'=> "modal", 'data-target'=> "#myModal", 'class'=> "new-type-button" } %>
    <%= render 'modals' %>
  </section>
</div>
<script>
  var pathname = window.location.pathname;
  var search_from_url = window.location.search
  var sum = pathname + search_from_url
  if (sum == '/types?show_all=true' ){
      $(".edit-button-type" ).hide();
      $(".destroy-button-type").hide();
      $(".new-type-button").hide();
  }
</script>

app/views/types/index.js.erb
$("#types-render").html("<%= j render partial: 'type', collection: @types %>")
$("#paginator").html("<%= j(paginate(@types, :remote => true))%>");

var pathname = window.location.pathname;
var search_from_url = window.location.search
var sum = pathname + search_from_url
if (sum == '/types?show_all=true' ){
    $(".edit-button-type" ).hide();
    $(".destroy-button-type").hide();
    $(".new-type-button").hide();
}

app/views/types/new.js.erb
$('#myModal').find(".modal-content").html("<%= j (render 'new', type: @type) %>");
$('#myModal').modal('show');

function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $('#image img').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}

$("#type-image-id-new").change(function(){
    readURL(this);
});

$("#close-button-new-type").click(function(e){
    $('#myModal').modal('hide');
});

$('#submit-button').click(function(){
    if($('#name-field').val() != '' ) {
        $('#myModal').modal('hide');
    }
});

app/views/types/show.js.erb
$('#modal-window-show').find(".modal-content").html("<%= j (render 'show', type: @type) %>");
$('#modal-window-show').modal('show');

$("#close-button-show-type").click(function(e){
    $('#modal-window-show').modal('hide');
});

app/views/types/update.js.erb
$('#<%= dom_id @type %>').replaceWith('<%= j render partial: "type", locals: {type: @type} %>');
$('#<%= dom_id @type %>').addClass("highlight");

setTimeout(function() {
    $( "tr" ).removeClass('highlight');
}, 1000);